n8n:
  replicaCount: 1
  
  image:
    tag: "2.0.2"
  
  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp2
  
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: n8n-testing.bancobasa.com.py
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: n8n-tls
        hosts:
          - n8n-testing.bancobasa.com.py
  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  env:
    N8N_HOST: "n8n-testing.bancobasa.com.py"
    N8N_PORT: "5678"
    N8N_PROTOCOL: "https"
    WEBHOOK_URL: "https://n8n-testing.bancobasa.com.py"
    
  nodeSelector: {}
  tolerations: []
  affinity: {}
