n8n:
  ingress:
    enabled: true
    className: "kong-gateway"
    hosts:
      - host: n8n.qa.bancobasa.com.py
        paths:
          - path: /
            pathType: ImplementationSpecific
  
  # main:
  #   persistence:
  #     enabled: true
  #     size: 10Gi
  #     accessMode: ReadWriteOnce
